language: 
	- cpp
sudo: 
    - required

compiler:
    - gcc

before_install:
    - sudo apt-get update
    
install:
    - sudo apt-get install -y g++
    - sudo apt-get install -y make
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

    - git clone https://github.com/opencv/opencv.git
    - git -C opencv checkout master

    - mkdir -p build && cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make -j4

    - sudo make install

    - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    - sudo ldconfig
    
    - cd ../../

before_script:
    - cd overlapDetection
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    
branches:
  only:
    - dev